package bwd.ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import bwd.action.Action;
import bwd.param.Param;
import bwd.util.ExcelException;

/**
 *
 * @author Administrator
 */
public class MainUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7357783601420337908L;

	/**
	 * Creates new form Login
	 */
	public MainUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jlbl_srcPathname = new javax.swing.JLabel();
		jtf_srcPathname = new javax.swing.JTextField();
		jbtn_srcChoose = new javax.swing.JButton();
		jlbl_srcSheet1name = new javax.swing.JLabel();
		jtf_srcSheet1name = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jlbl_destPath = new javax.swing.JLabel();
		jtf_destPath = new javax.swing.JTextField();
		jbtn_destChoose = new javax.swing.JButton();
		jlbl_destSheet1name = new javax.swing.JLabel();
		jtf_destSheet1name = new javax.swing.JTextField();
		jlbl_destSheet2name = new javax.swing.JLabel();
		jtf_destSheet2name = new javax.swing.JTextField();
		jlbl_destFilename = new javax.swing.JLabel();
		jtf_destFilename = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtp_showInfo = new javax.swing.JTextPane();
		jbtn_action = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Excel转换工具 v2.0");
		setBounds(new java.awt.Rectangle(200, 200, 400, 200));

		jLabel3.setFont(new java.awt.Font("微軟正黑體", 1, 14)); // NOI18N
		jLabel3.setText("源文件配置信息");

		jlbl_srcPathname.setText("源文件路径：");

		jtf_srcPathname.setEnabled(false);

		jbtn_srcChoose.setText("选择");
		jbtn_srcChoose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_srcChooseActionPerformed(evt);
			}
		});

		jlbl_srcSheet1name.setText("源文件sheet名：");

		jtf_srcSheet1name.setText("Report");

		jtf_destPath.setEnabled(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel3)
										.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jlbl_srcSheet1name,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jlbl_srcPathname,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jtf_srcPathname)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jbtn_srcChoose))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jtf_srcSheet1name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				160,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				240,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_srcPathname)
														.addComponent(
																jtf_srcPathname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jbtn_srcChoose))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_srcSheet1name)
														.addComponent(
																jtf_srcSheet1name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(0, 11, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("微軟正黑體", 1, 14)); // NOI18N
		jLabel1.setText("待生成文件配置信息");

		jlbl_destPath.setText("生成文件路径：");

		jbtn_destChoose.setText("选择");
		jbtn_destChoose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_destChooseActionPerformed(evt);
			}
		});

		jtf_destFilename.setText("abc.xls");

		jlbl_destSheet1name.setText("sheet1名称：");

		jtf_destSheet1name.setText("sheet1");

		jlbl_destSheet2name.setText("sheet2名称：");

		jtf_destSheet2name.setText("sheet2");

		jlbl_destFilename.setText("文件名：");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout.createSequentialGroup()
										.addComponent(jLabel1)
										.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(49, 49, 49)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jlbl_destSheet2name,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								83,
																								Short.MAX_VALUE)
																						.addComponent(
																								jlbl_destSheet1name,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jtf_destSheet2name,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								160,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jtf_destSheet1name,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								160,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jlbl_destFilename,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jlbl_destPath,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jtf_destPath)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jbtn_destChoose))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jtf_destFilename,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												160,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(0,
																												243,
																												Short.MAX_VALUE)))))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_destPath)
														.addComponent(
																jtf_destPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jbtn_destChoose))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_destFilename)
														.addComponent(
																jtf_destFilename,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_destSheet1name)
														.addComponent(
																jtf_destSheet1name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jlbl_destSheet2name)
														.addComponent(
																jtf_destSheet2name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(16, 16, 16)));


		jbtn_action.setFont(new java.awt.Font("微軟正黑體", 1, 18)); // NOI18N
		jbtn_action.setText("开始转化");
		jbtn_action.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_actionActionPerformed(evt);
			}
		});

		jtp_showInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jScrollPane1.setViewportView(jtp_showInfo);

		jLabel5.setFont(new java.awt.Font("微軟正黑體", 1, 14)); // NOI18N
		jLabel5.setText("显示信息");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jScrollPane1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jbtn_action,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												142,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
						.addGroup(
								jPanel3Layout.createSequentialGroup()
										.addComponent(jLabel5)
										.addGap(0, 0, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(jLabel5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jbtn_action,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																116,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(45, 45, 45)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel2,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel3,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addGap(69, 69, 69)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(11, Short.MAX_VALUE)));

		getAccessibleContext().setAccessibleDescription("");

		pack();
	}// </editor-fold>

	private void btn_srcChooseActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser jfc = new JFileChooser();
		jfc.setDialogTitle("请选择源文件");
		jfc.addChoosableFileFilter(new FileNameExtensionFilter("Excel格式",
				"xls", "xlsx"));
		if (JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this)) {
			this.jtf_srcPathname.setText(jfc.getSelectedFile()
					.getAbsolutePath());
			// System.out.println("打开文件路径为：" +
			// jfc.getSelectedFile().getAbsolutePath());
		}
	}

	private void btn_destChooseActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser jfc = new JFileChooser();
		jfc.setDialogTitle("请选择目标文件夹");
		jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		if (JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this)) {
			if (jfc.getSelectedFile().isDirectory()) {
				this.jtf_destPath.setText(jfc.getSelectedFile()
						.getAbsolutePath());
				// System.out.println("打开文件路径为：" +
				// jfc.getSelectedFile().getAbsolutePath());
			}
		}
	}

	private void btn_actionActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			checkParam();

			Param.setSrcPathname(this.jtf_srcPathname.getText().trim());
			Param.setSrcSheet1Name(this.jtf_srcSheet1name.getText().trim());
			Param.setDestPathname(this.jtf_destPath.getText().trim() + "\\"
					+ this.jtf_destFilename.getText().trim());
			Param.setDestSheet1Name(this.jtf_destSheet1name.getText().trim());
			Param.setDestSheet2Name(this.jtf_destSheet2name.getText().trim());

			new Action().action();
			this.jtp_showInfo.setText("生成成功！\r\n" + "生成文件路径为："
					+ Param.getDestPathname());
		} catch (ExcelException e1) {
			this.jtp_showInfo.setText(e1.getMessage());
		}
	}

	private void checkParam() throws ExcelException {
		if ((null == this.jtf_srcPathname)
				|| ("".equals(this.jtf_srcPathname.getText().trim()))) {
			throw new ExcelException(this.jlbl_srcPathname.getText() + " 错误!");
		} else if (!(this.jtf_srcPathname.getText().trim().endsWith("xls") || this.jtf_srcPathname
				.getText().trim().endsWith("xlsx"))) {
			throw new ExcelException(this.jlbl_srcPathname.getText()
					+ " 文件后缀名错误！应该以\"xls\"或者\"xlsx\"结尾");
		}
		if ((null == this.jtf_srcSheet1name)
				|| ("".equals(this.jtf_srcSheet1name.getText().trim()))) {
			throw new ExcelException(this.jlbl_srcSheet1name.getText() + " 错误!");
		}
		if ((null == this.jtf_destPath)
				|| ("".equals(this.jtf_destPath.getText().trim()))) {
			throw new ExcelException(this.jlbl_destPath.getText() + " 错误!");
		}
		if ((null == this.jtf_destFilename)
				|| ("".equals(this.jtf_destFilename.getText().trim()))) {
			throw new ExcelException(this.jlbl_destFilename.getText() + " 错误!");
		} else if (!(this.jtf_destFilename.getText().trim().endsWith("xls") || this.jtf_destFilename
				.getText().trim().endsWith("xlsx"))) {
			throw new ExcelException(this.jlbl_destFilename.getText()
					+ " 文件后缀名错误！应该以\"xls\"或者\"xlsx\"结尾");
		}
		if ((null == this.jtf_destSheet1name)
				|| ("".equals(this.jtf_destSheet1name.getText().trim()))) {
			throw new ExcelException(this.jlbl_destSheet1name.getText()
					+ " 错误!");
		}
		if ((null == this.jtf_destSheet2name)
				|| ("".equals(this.jtf_destSheet2name.getText().trim()))) {
			throw new ExcelException(this.jlbl_destSheet2name.getText()
					+ " 错误!");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jbtn_action;
	private javax.swing.JButton jbtn_destChoose;
	private javax.swing.JButton jbtn_srcChoose;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jlbl_destSheet2name;
	private javax.swing.JLabel jlbl_srcPathname;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jlbl_destFilename;
	private javax.swing.JLabel jlbl_srcSheet1name;
	private javax.swing.JLabel jlbl_destPath;
	private javax.swing.JLabel jlbl_destSheet1name;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jtf_destFilename;
	private javax.swing.JTextField jtf_destPath;
	private javax.swing.JTextField jtf_destSheet1name;
	private javax.swing.JTextField jtf_destSheet2name;
	private javax.swing.JTextField jtf_srcPathname;
	private javax.swing.JTextField jtf_srcSheet1name;
	private javax.swing.JTextPane jtp_showInfo;
	// End of variables declaration

}
